"""Add MFA fields to User

Revision ID: 1664ca3ca762
Revises: 0dce83180670
Create Date: 2026-01-04 09:07:52.269253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1664ca3ca762'
down_revision: Union[str, Sequence[str], None] = '0dce83180670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mfa_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('mfa_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'mfa_enabled')
    op.drop_column('user', 'mfa_secret')
    # ### end Alembic commands ###
