"""add system settings table

Revision ID: 983e797d3862
Revises: ebb25fb161d4
Create Date: 2026-01-03 16:40:49.094786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '983e797d3862'
down_revision: Union[str, Sequence[str], None] = 'ebb25fb161d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('systemsetting',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ref_code', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_systemsetting_key'), 'systemsetting', ['key'], unique=True)
    op.create_index(op.f('ix_systemsetting_ref_code'), 'systemsetting', ['ref_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_systemsetting_ref_code'), table_name='systemsetting')
    op.drop_index(op.f('ix_systemsetting_key'), table_name='systemsetting')
    op.drop_table('systemsetting')
    # ### end Alembic commands ###
