"""add_gender_to_subject

Revision ID: d8b17bba5b7b
Revises: 791112025046
Create Date: 2026-01-02 22:21:34.550424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd8b17bba5b7b'
down_revision: Union[str, Sequence[str], None] = '791112025046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('event', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('procedure', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('procedure', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('study', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('study', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('subject', sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('subject', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subject', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subject', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subject', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('subject', 'gender')
    op.alter_column('study', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('study', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('procedure', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('procedure', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('event', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('event', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
